import "../styles/globals.css"
import { ThemeProvider } from "next-themes"
import Head from "next/head"

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider attribute="class" defaultTheme="light">
      <Head>
        <title>my-phone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
    // <Component {...pageProps} />
  )
}

export default MyApp
